import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  
  
  return (
    <html lang="en">
      <body
        className="
          flex
          flex-col
          min-h-screen
          justify-center
          items-center

        
        "  
      >



        <header>
          <h1>Next.js ❤️ React</h1>
          <nav>
            <Link href="/">home</Link>
            <Link href="/route">route</Link>
            <Link href="/caracteristicas">caracteristicas</Link>
          </nav>

        </header>
        
        <main className="bg-pink-300 w" >
          
          {children}
        </main>

        <footer>diw</footer>
        
      
      </body>
    </html>
  );
}
